Homework1: Olga Kosmacheva
belovmd/it-academy-bps pull request #10
Opened 2021-01-24 17:29 UTC by OlgaKosm

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-02-20 16:17 UTC, belovmd requested changes
Спасибо за Вашу работу. 

Критерии оценки домашней работы можно прочитать тут: [Review Notes](https://github.com/belovmd/it-academy-bps/blob/master/review_notes/homework_evaluation.md). 
Обратите внимание на следующие замечания:
- Пожалуйста, помещайте описание задач перед задачей. В данном случае это будет что-то такое: `"""# 5 lines: Functions"""`

2021-02-20 16:17 UTC, belovmd commented on src/homework1.py
> +
Рационально писать код следующим образом: 
```
pass  # last line of previous task


# next task docstring
pass  # my next task first line  
```

2021-02-20 16:17 UTC, belovmd commented on src/homework1.py
> +greet('Jack')
Здесь код задачи greet имеет отступ от функции в 2 строки. При этом расстояние между задачами friends и parents всего одна строка. В целом, из-за этого файл выглядит неаккуратно. 
Рационально разделять задачи двумя строками везде, а код задачи не более чем одной строкой.

2021-02-20 16:17 UTC, belovmd commented on src/homework1.py
> +# This program adds up integers that have been passed as arguments in the command line
Здесь описание задачи которая решается имеет отступ 1 строку от предыдущей задачи, и 2 до своей задачи. Это нелогично

2021-02-20 16:17 UTC, belovmd commented on src/homework1.py
> +# glob supports Unix style pathname extensions
условия задачи рационально помещать как докстринг в `"""`

2021-02-27 10:10 UTC, OlgaKosm commented on src/homework1.py
> +
Описание задач добавлено, все задачи отделены 2 строками

2021-02-27 10:13 UTC, OlgaKosm commented on src/homework1.py
> +greet('Jack')
В данной задаче, если поставить 1 строку перед greet появляется сообщение pep8, требует 2 строки

2021-02-27 10:13 UTC, OlgaKosm commented on src/homework1.py
> +# This program adds up integers that have been passed as arguments in the command line
Теперь все задачи отделены 2 строками

2021-02-27 10:14 UTC, OlgaKosm commented on src/homework1.py
> +# glob supports Unix style pathname extensions
условие помещено как докстринг

2021-03-01 19:28 UTC, belovmd approved these changes
+1

2021-03-01 19:29 UTC, belovmd commented
Отличная работа

2021-03-01 19:29 UTC, closed without merging